### ISSUE TITLE
background color makes icon invisible

### ISSUE THREAD

**Issue by jonenst** [coinchoid/coinchoid-web#10]
- On android on the task switcher
- I also saw it some place else but can't remember..

**Comment by aucoeurdavignon** [comment]
![tmp_9780-screenshot_20161012-1334561300543083](https://cloud.githubusercontent.com/assets/20490527/19310436/537cede4-908a-11e6-8c8f-804930aa550b.png)

It was on the firefox home screen

**Comment by jonenst** [comment]
Fixed, although firefox switched to displaying à preview of the app. I don't know why. I think firefox doesn't use the manifest to get à background color, instead it computes a
![Uploading tmp_21351-Screenshot_20161017-135741325156314.png…]()
 dominant color from the icon .

**Comment by jonenst** [comment]
![tmp_21351-screenshot_20161017-1357411600273821](https://cloud.githubusercontent.com/assets/89208/19436787/6dc392d4-9472-11e6-8f3d-2e73d18ae24e.png)
